/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routers/__root'
import { Route as Char123Site_nameChar125RouteImport } from './routers/{-$site_name}'
import { Route as Char123Site_nameChar125IndexRouteImport } from './routers/{-$site_name}/index'
import { Route as Char123Site_nameChar125InventoryRouteImport } from './routers/{-$site_name}/inventory'
import { Route as Char123Site_nameChar125DiceshockAgentsRouteImport } from './routers/{-$site_name}/diceshock-agents'
import { Route as Char123Site_nameChar125ContactUsRouteImport } from './routers/{-$site_name}/contact-us'

const Char123Site_nameChar125Route = Char123Site_nameChar125RouteImport.update({
  id: '/{-$site_name}',
  path: '/{-$site_name}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123Site_nameChar125IndexRoute =
  Char123Site_nameChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123Site_nameChar125Route,
  } as any)
const Char123Site_nameChar125InventoryRoute =
  Char123Site_nameChar125InventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => Char123Site_nameChar125Route,
  } as any)
const Char123Site_nameChar125DiceshockAgentsRoute =
  Char123Site_nameChar125DiceshockAgentsRouteImport.update({
    id: '/diceshock-agents',
    path: '/diceshock-agents',
    getParentRoute: () => Char123Site_nameChar125Route,
  } as any)
const Char123Site_nameChar125ContactUsRoute =
  Char123Site_nameChar125ContactUsRouteImport.update({
    id: '/contact-us',
    path: '/contact-us',
    getParentRoute: () => Char123Site_nameChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$site_name}': typeof Char123Site_nameChar125RouteWithChildren
  '/{-$site_name}/contact-us': typeof Char123Site_nameChar125ContactUsRoute
  '/{-$site_name}/diceshock-agents': typeof Char123Site_nameChar125DiceshockAgentsRoute
  '/{-$site_name}/inventory': typeof Char123Site_nameChar125InventoryRoute
  '/{-$site_name}/': typeof Char123Site_nameChar125IndexRoute
}
export interface FileRoutesByTo {
  '/{-$site_name}/contact-us': typeof Char123Site_nameChar125ContactUsRoute
  '/{-$site_name}/diceshock-agents': typeof Char123Site_nameChar125DiceshockAgentsRoute
  '/{-$site_name}/inventory': typeof Char123Site_nameChar125InventoryRoute
  '/{-$site_name}': typeof Char123Site_nameChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$site_name}': typeof Char123Site_nameChar125RouteWithChildren
  '/{-$site_name}/contact-us': typeof Char123Site_nameChar125ContactUsRoute
  '/{-$site_name}/diceshock-agents': typeof Char123Site_nameChar125DiceshockAgentsRoute
  '/{-$site_name}/inventory': typeof Char123Site_nameChar125InventoryRoute
  '/{-$site_name}/': typeof Char123Site_nameChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$site_name}'
    | '/{-$site_name}/contact-us'
    | '/{-$site_name}/diceshock-agents'
    | '/{-$site_name}/inventory'
    | '/{-$site_name}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$site_name}/contact-us'
    | '/{-$site_name}/diceshock-agents'
    | '/{-$site_name}/inventory'
    | '/{-$site_name}'
  id:
    | '__root__'
    | '/{-$site_name}'
    | '/{-$site_name}/contact-us'
    | '/{-$site_name}/diceshock-agents'
    | '/{-$site_name}/inventory'
    | '/{-$site_name}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123Site_nameChar125Route: typeof Char123Site_nameChar125RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$site_name}': {
      id: '/{-$site_name}'
      path: '/{-$site_name}'
      fullPath: '/{-$site_name}'
      preLoaderRoute: typeof Char123Site_nameChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$site_name}/': {
      id: '/{-$site_name}/'
      path: '/'
      fullPath: '/{-$site_name}/'
      preLoaderRoute: typeof Char123Site_nameChar125IndexRouteImport
      parentRoute: typeof Char123Site_nameChar125Route
    }
    '/{-$site_name}/inventory': {
      id: '/{-$site_name}/inventory'
      path: '/inventory'
      fullPath: '/{-$site_name}/inventory'
      preLoaderRoute: typeof Char123Site_nameChar125InventoryRouteImport
      parentRoute: typeof Char123Site_nameChar125Route
    }
    '/{-$site_name}/diceshock-agents': {
      id: '/{-$site_name}/diceshock-agents'
      path: '/diceshock-agents'
      fullPath: '/{-$site_name}/diceshock-agents'
      preLoaderRoute: typeof Char123Site_nameChar125DiceshockAgentsRouteImport
      parentRoute: typeof Char123Site_nameChar125Route
    }
    '/{-$site_name}/contact-us': {
      id: '/{-$site_name}/contact-us'
      path: '/contact-us'
      fullPath: '/{-$site_name}/contact-us'
      preLoaderRoute: typeof Char123Site_nameChar125ContactUsRouteImport
      parentRoute: typeof Char123Site_nameChar125Route
    }
  }
}

interface Char123Site_nameChar125RouteChildren {
  Char123Site_nameChar125ContactUsRoute: typeof Char123Site_nameChar125ContactUsRoute
  Char123Site_nameChar125DiceshockAgentsRoute: typeof Char123Site_nameChar125DiceshockAgentsRoute
  Char123Site_nameChar125InventoryRoute: typeof Char123Site_nameChar125InventoryRoute
  Char123Site_nameChar125IndexRoute: typeof Char123Site_nameChar125IndexRoute
}

const Char123Site_nameChar125RouteChildren: Char123Site_nameChar125RouteChildren =
  {
    Char123Site_nameChar125ContactUsRoute:
      Char123Site_nameChar125ContactUsRoute,
    Char123Site_nameChar125DiceshockAgentsRoute:
      Char123Site_nameChar125DiceshockAgentsRoute,
    Char123Site_nameChar125InventoryRoute:
      Char123Site_nameChar125InventoryRoute,
    Char123Site_nameChar125IndexRoute: Char123Site_nameChar125IndexRoute,
  }

const Char123Site_nameChar125RouteWithChildren =
  Char123Site_nameChar125Route._addFileChildren(
    Char123Site_nameChar125RouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123Site_nameChar125Route: Char123Site_nameChar125RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
