"$schema"= "node_modules/wrangler/config-schema.json"

name = "diceshock-behover"
compatibility_date= "2025-09-24"
main= "./src/main.tsx"
compatibility_flags= ["nodejs_compat"]

[version_metadata]
binding = "CF_VERSION_METADATA"
