/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomePageRouteImport } from './routes/_home-page'
import { Route as _notFoundRouteImport } from './routes/__not-found'
import { Route as HomePageIndexRouteImport } from './routes/_home-page/index'

const HomePageRoute = HomePageRouteImport.update({
  id: '/_home-page',
  getParentRoute: () => rootRouteImport,
} as any)
const _notFoundRoute = _notFoundRouteImport.update({
  id: '/__not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const HomePageIndexRoute = HomePageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomePageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomePageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof HomePageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__not-found': typeof _notFoundRoute
  '/_home-page': typeof HomePageRouteWithChildren
  '/_home-page/': typeof HomePageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/__not-found' | '/_home-page' | '/_home-page/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _notFoundRoute: typeof _notFoundRoute
  HomePageRoute: typeof HomePageRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home-page': {
      id: '/_home-page'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__not-found': {
      id: '/__not-found'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _notFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home-page/': {
      id: '/_home-page/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomePageIndexRouteImport
      parentRoute: typeof HomePageRoute
    }
  }
}

interface HomePageRouteChildren {
  HomePageIndexRoute: typeof HomePageIndexRoute
}

const HomePageRouteChildren: HomePageRouteChildren = {
  HomePageIndexRoute: HomePageIndexRoute,
}

const HomePageRouteWithChildren = HomePageRoute._addFileChildren(
  HomePageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _notFoundRoute: _notFoundRoute,
  HomePageRoute: HomePageRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
